### ISSUE TITLE
New BaseX version available 10.3

### ISSUE THREAD

**Issue by kumy** [Quodatum/basex-docker#5]
Thanks for your work on those images. Are there any plans to also build images for `v10.x`?
Thanks

**Comment by apb2006** [comment]
Hi, yes I plan to build images for 10.3 with a recent Java version. I am away at the moment hopefully it be available early November.

**Comment by apb2006** [comment]
See https://github.com/Quodatum/basex-docker/tree/basex-10.3#readme
